# Generated by Django 5.2.1 on 2025-05-29 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Material')),
                ('type', models.CharField(choices=[('Filament', 'Filamento'), ('Resin', 'Resina'), ('Powder', 'Pó'), ('Other', 'Outro')], max_length=50, verbose_name='Tipo')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo por Unidade')),
                ('unit_of_measure', models.CharField(choices=[('kg', 'Quilogramas (kg)'), ('g', 'Gramas (g)'), ('L', 'Litros (L)'), ('mL', 'Mililitros (mL)'), ('unit', 'Unidade')], max_length=10, verbose_name='Unidade de Medida')),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Quantidade em Estoque')),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Nível Mínimo de Estoque')),
                ('properties_text', models.TextField(blank=True, null=True, verbose_name='Propriedades (Texto)')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome/ID da Impressora')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fabricante')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('printing', 'Imprimindo'), ('maintenance', 'Manutenção'), ('offline', 'Offline'), ('error', 'Erro')], default='offline', max_length=50, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização')),
                ('date_acquired', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Fornecedor')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pessoa de Contato')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Modelo/Peça')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='parts/', verbose_name='Arquivo do Modelo')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Modelo 3D (Peça)',
                'verbose_name_plural': 'Modelos 3D (Peças)',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('approved', 'Aprovado'), ('queued', 'Na Fila'), ('printing', 'Imprimindo'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='requested', max_length=50, verbose_name='Status')),
                ('estimated_print_time', models.DurationField(blank=True, null=True, verbose_name='Tempo Estimado')),
                ('actual_print_time', models.DurationField(blank=True, null=True, verbose_name='Tempo Real')),
                ('estimated_material_usage', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Material Estimado')),
                ('actual_material_usage', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Material Real')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Estimado')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Real')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Início da Impressão')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Impressão')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.material', verbose_name='Material Utilizado')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part', verbose_name='Peça')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.printer', verbose_name='Impressora Designada')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Pedido de Impressão',
                'verbose_name_plural': 'Pedidos de Impressão',
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier', verbose_name='Fornecedor'),
        ),
    ]
